### ISSUE TITLE
Realizar web provicional html + css + js 

### ISSUE THREAD

**Issue by adminAgenciaServitec** [Agencia-Servitec/gamontllantas#1]
- [x] Usar el template de hankook
- [x] Reemplazar todo el contenido de hankook por el contenido de gamontLlantas
- [x] Verificar estadisticas en LightHouse 
- [x] Testear la web y verificar que no aya bugs
- [x] Reemplazar api de envio de emails por la api nueva (aun esta en proceso dejar esta tarea en pendiente)
- [x] Subir web de gamont llantas al servidor
- [x] Agregar un campo nuevo con el id "countryCode" en el formulario contacto, por defecto que este seleccionado Perú:

![Screen Shot 2022-06-07 at 10 21 17 AM](https://user-images.githubusercontent.com/104750139/172419091-3908362f-6ab9-4578-a261-f77451cc3b83.png)
![Screen Shot 2022-06-07 at 10 22 55 AM](https://user-images.githubusercontent.com/104750139/172419103-8fda23f9-a9f4-4cbc-8112-215a7c0a2471.png)

**Comment by angelgt28** [comment]
-requirimientos realizados
