### ISSUE TITLE
Crear email templates para gamont llantas

### ISSUE THREAD

**Issue by adminAgenciaServitec** [Agencia-Servitec/gamontllantas#2]
- [x] Crear template emails para el emisor
- [x] Crear template emails para el receptor

- Usar las siguiente web para diseñar:
     -  https://pro.beefree.io/login
     - https://unlayer.com/

### Template email para el emisor:
![Screen Shot 2022-06-06 at 1 01 01 AM](https://user-images.githubusercontent.com/104750139/172103982-6b3837ed-a1ae-4dcb-80de-1006b87be955.png)

### Template email para el receptor:
![Screen Shot 2022-06-06 at 1 01 36 AM](https://user-images.githubusercontent.com/104750139/172104059-0ef402de-69de-4f45-b1ed-bdd7e5b56385.png)

**Comment by EduardXI** [comment]
Templates email
![Captura de pantalla 2022-06-08 a la(s) 16 25 52](https://user-images.githubusercontent.com/104872080/172733602-39a9f0c8-2dba-41f4-b9e9-3118344249cb.png)
![Captura de pantalla 2022-06-08 a la(s) 18 23 37](https://user-images.githubusercontent.com/104872080/172733609-67c9f3cb-4fa3-445b-afba-c288560f2279.png)

s
