### ISSUE TITLE
Update landing

### ISSUE THREAD

**Issue by adminAgenciaServitec** [Agencia-Servitec/gamontllantas#3]
- [x] Actualizar boton flotante "Contácto", menos margin-left, background: #ffd200, color: negro:
![Screen Shot 2022-06-09 at 9 08 27 AM](https://user-images.githubusercontent.com/104750139/172866823-69696173-6d7e-4cdd-b18a-10c3f080fe9f.png)

Debe quedar asi:
![Screen Shot 2022-06-09 at 12 14 34 PM](https://user-images.githubusercontent.com/104750139/172905640-e100aac7-a56c-4a2f-a6ef-c7dd0eb2c5df.png)

- [x] Quitar 1 icon, solo dejar 1 icon del lado izquierdo, en estos botones
![Screen Shot 2022-06-09 at 9 17 09 AM](https://user-images.githubusercontent.com/104750139/172868760-03468a86-6bda-42a9-b57b-03fec69ff949.png)

- [x] Solo visible en mobile, con margin-top o padding-top de 1rem:
![Screen Shot 2022-06-09 at 9 11 31 AM](https://user-images.githubusercontent.com/104750139/172867449-0d440bf6-0e0c-4ff4-8696-8e0e01c1e10e.png)

## Mejorar UI en mobile:

- [x] Reducir un poco el padding de menu lista de mobile 
![Screen Shot 2022-06-09 at 9 13 49 AM](https://user-images.githubusercontent.com/104750139/172868067-ba888037-6df2-487c-ace9-66f4e93af970.png)

- [x] Centrar textos en mobile
![Screen Shot 2022-06-09 at 10 00 26 AM](https://user-images.githubusercontent.com/104750139/172878456-757d0226-c32f-4cdd-ba11-fcedd4307bb3.png) 

- [x] Modificar el diseño de boton wsp en mobile:
![Screen Shot 2022-06-09 at 12 08 31 PM](https://user-images.githubusercontent.com/104750139/172904424-dc27c1da-8c20-4e03-9a15-29bba0192aa1.png)

**Comment by angelgt28** [comment]
finish
